_target_: src.ds.iwslt17.IWSLT17
source: ${experiment.source}
target: ${experiment.target}
is_encoder_decoder: ${model.is_encoder_decoder}
train_batch_size: ${experiment.train_batch_size}
val_batch_size: ${experiment.val_batch_size}
test_batch_size: ${experiment.test_batch_size}