# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: "${run_name}" 
  save_dir: "${paths.output_dir}"
  offline: False
  id: null # pass correct id to resume experiment!
  project: "thesis"
  entity: "hugo-pitorro"
  group: ""
  tags: []
  job_type: ""
