defaults:
  - model_checkpoint
  # - early_stopping
  # - model_summary
  # - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:02d}-{val_bleu:.2f}"
  monitor: "val_bleu"
  mode: "max"
  save_last: True
  save_top_k: 2

